import { Message, MessageEmbed } from "discord.js";
import { INSPIRE_URL } from "../../lib/constants";
import { ApplyOptions } from "@sapphire/decorators";
import { Command, CommandOptions } from "@sapphire/framework";
import { send } from "@sapphire/plugin-editable-commands";
import { config } from "../../lib/config";
import { fetch, FetchResultTypes } from "@sapphire/fetch";

@ApplyOptions<CommandOptions>(
  config.applyConfig("inspire", {
    description:
      "Images generated by AI... how could things possibly go wrong?",
    preconditions: ["GuildOnly"],
  }),
)
export class InspireCommand extends Command {
  async messageRun(msg: Message) {
    INSPIRE_URL.search = new URLSearchParams({ generate: "true" }).toString();

    const res = await fetch(INSPIRE_URL, FetchResultTypes.Text);

    if (res) {
      return send(msg, {
        embeds: [
          new MessageEmbed()
            .setURL("https://inspirobot.me")
            .setImage(res)
            .setColor("#6dd3ff"),
        ],
      });
    }

    return send(msg, "It seems something went wrong, try again later?");
  }
}
