import { MessageEmbed } from "discord.js";
import { INSPIRE_URL } from "../../lib/constants";
import { ApplyOptions } from "@sapphire/decorators";
import { ApplicationCommandRegistry, Command } from "@sapphire/framework";
import { config } from "../../lib/config";
import { fetch, FetchResultTypes } from "@sapphire/fetch";

@ApplyOptions(
  config.applyConfig("inspire", {
    description:
      "Images generated by AI... how could things possibly go wrong?",
    preconditions: ["GuildOnly"],
  }),
)
export class InspireCommand extends Command {
  public override registerApplicationCommands(
    registry: ApplicationCommandRegistry,
  ) {
    registry.registerChatInputCommand((builder) => {
      builder.setName(this.name).setDescription(this.description);
    });
  }

  public override async chatInputRun(
    interaction: Command.ChatInputInteraction,
  ) {
    try {
      INSPIRE_URL.search = new URLSearchParams({ generate: "true" }).toString();

      const res = await fetch(INSPIRE_URL, FetchResultTypes.Text);

      if (res) {
        return interaction.reply({
          embeds: [
            new MessageEmbed()
              .setURL("https://inspirobot.me")
              .setImage(res)
              .setColor("#6dd3ff"),
          ],
        });
      }
    } catch (e) {
      return interaction.reply({
        ephemeral: true,
        content: "It seems something went wrong, try again later?",
      });
    }
  }
}
