import { ApplyOptions } from "@sapphire/decorators";
import { FetchResultTypes, fetch } from "@sapphire/fetch";
import {
  type ApplicationCommandRegistry,
  Command,
  type CommandOptions,
} from "@sapphire/framework";
import { send } from "@sapphire/plugin-editable-commands";
import {
  type ChatInputCommandInteraction,
  EmbedBuilder,
  type Message,
} from "discord.js";
import { config } from "../../lib/config";
import { INSPIRE_URL } from "../../lib/constants";
import { registerSlash } from "../../lib/registry";

@ApplyOptions<CommandOptions>(
  config.applyConfig("inspire", {
    description:
      "Images generated by AI... how could things possibly go wrong?",
    preconditions: ["GuildOnly"],
  }),
)
export class InspireCommand extends Command {
  public override async messageRun(msg: Message) {
    INSPIRE_URL.search = new URLSearchParams({ generate: "true" }).toString();

    const res = await fetch(INSPIRE_URL, FetchResultTypes.Text);

    if (res) {
      return send(msg, {
        embeds: [
          new EmbedBuilder()
            .setURL("https://inspirobot.me")
            .setImage(res)
            .setColor("#6dd3ff"),
        ],
      });
    }

    return send(msg, "It seems something went wrong, try again later?");
  }

  public override async chatInputRun(interaction: ChatInputCommandInteraction) {
    INSPIRE_URL.search = new URLSearchParams({ generate: "true" }).toString();

    const res = await fetch(INSPIRE_URL, FetchResultTypes.Text);
    if (!res)
      return interaction.reply({
        content: "Something went wrong, try again later?",
        flags: ["Ephemeral"],
      });

    return interaction.reply({
      embeds: [
        new EmbedBuilder()
          .setURL("https://inspirobot.me")
          .setImage(res)
          .setColor("#6dd3ff"),
      ],
    });
  }

  public override registerApplicationCommands(
    registry: ApplicationCommandRegistry,
  ) {
    registerSlash(registry, (b) => {
      b.setName(this.name).setDescription(this.description);
      return b;
    });
  }
}
