import { Command, CommandoClient, CommandoMessage } from "discord.js-commando";
import { config } from "../../config";
import { MessageEmbed } from "discord.js";
import got from "got";

const url = "http://inspirobot.me/api";

export default class InspireCommand extends Command {
  constructor(client: CommandoClient) {
    super(client, {
      name: "inspire",
      group: "fun",
      memberName: "inspire",
      description:
        "Images generated by AI... how could things possibly go wrong?",
      guildOnly: true,
      throttling: {
        usages: config.commands.inspire.rateLimit,
        duration: 120,
      },
    });
  }

  async run(msg: CommandoMessage) {
    const { body } = await got.get(url, { searchParams: { generate: true } });

    if (body) {
      return msg.embed(
        new MessageEmbed()
          .setURL("https://inspirobot.me")
          .setImage(body)
          .setColor("#6dd3ff")
      );
    }

    return msg.say("It seems something went wrong, try again later?");
  }
}
