version: "3"

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000
    volumes:
      - ..:/buster:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    user: node
  redis:
    image: redis:latest
    command: redis-server --save 60 1 --loglevel warning
    ports:
      - 6379:6379
    restart: unless-stopped
    volumes:
      - redis-data:/data

volumes:
  redis-data:
